modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${license}"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${mod_name}"
logoFile="${modid}.png"
authors="${author}"
description='''${mod_description}'''

[[dependencies.${modid}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_dep}"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="cloth_config"
mandatory=false
versionRange="[${cloth_version},)"
ordering="BEFORE"
side="CLIENT"